<a href="https://colab.research.google.com/github/ramoants254/Binary-Classification-using-ANN-/blob/main/Binary_Classification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Importing essential Libraries

In [74]:
import tensorflow as tf
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
from sklearn.preprocessing import StandardScaler

## Data Preprocessing

In [36]:
df=pd.read_csv('/content/drive/MyDrive/Churn_Modelling.csv')
df.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [37]:
df.shape

(10000, 14)

In [38]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   RowNumber        10000 non-null  int64  
 1   CustomerId       10000 non-null  int64  
 2   Surname          10000 non-null  object 
 3   CreditScore      10000 non-null  int64  
 4   Geography        10000 non-null  object 
 5   Gender           10000 non-null  object 
 6   Age              10000 non-null  int64  
 7   Tenure           10000 non-null  int64  
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64  
 10  HasCrCard        10000 non-null  int64  
 11  IsActiveMember   10000 non-null  int64  
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64  
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB


In [39]:
df.describe()

RowNumber    CustomerId   CreditScore           Age        Tenure  \
count  10000.00000  1.000000e+04  10000.000000  10000.000000  10000.000000   
mean    5000.50000  1.569094e+07    650.528800     38.921800      5.012800   
std     2886.89568  7.193619e+04     96.653299     10.487806      2.892174   
min        1.00000  1.556570e+07    350.000000     18.000000      0.000000   
25%     2500.75000  1.562853e+07    584.000000     32.000000      3.000000   
50%     5000.50000  1.569074e+07    652.000000     37.000000      5.000000   
75%     7500.25000  1.575323e+07    718.000000     44.000000      7.000000   
max    10000.00000  1.581569e+07    850.000000     92.000000     10.000000   

             Balance  NumOfProducts    HasCrCard  IsActiveMember  \
count   10000.000000   10000.000000  10000.00000    10000.000000   
mean    76485.889288       1.530200      0.70550        0.515100   
std     62397.405202       0.581654      0.45584        0.499797   
min         0.000000       1.000000      0.00000        0.000000   
25%         0.000000       1.000000      0.00000        0.000000   
50%     97198.540000       1.000000      1.00000        1.000000   
75%    127644.240000       2.000000      1.00000        1.000000   
max    250898.090000       4.000000      1.00000        1.000000   

       EstimatedSalary        Exited  
count     10000.000000  10000.000000  
mean     100090.239881      0.203700  
std       57510.492818      0.402769  
min          11.580000      0.000000  
25%       51002.110000      0.000000  
50%      100193.915000      0.000000  
75%      149388.247500      0.000000  
max      199992.480000      1.000000

In [40]:
df.isnull().sum()

RowNumber          0
CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [41]:
df.head().T

0          1          2         3          4
RowNumber                1          2          3         4          5
CustomerId        15634602   15647311   15619304  15701354   15737888
Surname           Hargrave       Hill       Onio      Boni   Mitchell
CreditScore            619        608        502       699        850
Geography           France      Spain     France    France      Spain
Gender              Female     Female     Female    Female     Female
Age                     42         41         42        39         43
Tenure                   2          1          8         1          2
Balance                0.0   83807.86   159660.8       0.0  125510.82
NumOfProducts            1          1          3         2          1
HasCrCard                1          0          1         0          1
IsActiveMember           1          1          0         0          1
EstimatedSalary  101348.88  112542.58  113931.57  93826.63    79084.1
Exited                   1          0          1         0          0

In [42]:
new_df = df.drop(columns=['Surname', 'CustomerId', 'RowNumber'])


In [43]:
new_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   CreditScore      10000 non-null  int64  
 1   Geography        10000 non-null  object 
 2   Gender           10000 non-null  object 
 3   Age              10000 non-null  int64  
 4   Tenure           10000 non-null  int64  
 5   Balance          10000 non-null  float64
 6   NumOfProducts    10000 non-null  int64  
 7   HasCrCard        10000 non-null  int64  
 8   IsActiveMember   10000 non-null  int64  
 9   EstimatedSalary  10000 non-null  float64
 10  Exited           10000 non-null  int64  
dtypes: float64(2), int64(7), object(2)
memory usage: 859.5+ KB


In [44]:
new_df=pd.get_dummies(data=new_df,drop_first=True)

In [45]:
new_df.head()

CreditScore  Age  Tenure    Balance  NumOfProducts  HasCrCard  \
0          619   42       2       0.00              1          1   
1          608   41       1   83807.86              1          0   
2          502   42       8  159660.80              3          1   
3          699   39       1       0.00              2          0   
4          850   43       2  125510.82              1          1   

   IsActiveMember  EstimatedSalary  Exited  Geography_Germany  \
0               1        101348.88       1              False   
1               1        112542.58       0              False   
2               0        113931.57       1              False   
3               0         93826.63       0              False   
4               1         79084.10       0              False   

   Geography_Spain  Gender_Male  
0            False        False  
1             True        False  
2            False        False  
3            False        False  
4             True        False

In [46]:
new_df.shape

(10000, 12)

## Spliting the Data to training and testing sets and Feature Scaling

In [47]:
x=new_df.drop('Exited',axis=1)
y=new_df['Exited']

In [48]:
sc=StandardScaler()
x=sc.fit_transform(x)

In [49]:
x

array([[-0.32622142,  0.29351742, -1.04175968, ..., -0.57873591,
        -0.57380915, -1.09598752],
       [-0.44003595,  0.19816383, -1.38753759, ..., -0.57873591,
         1.74273971, -1.09598752],
       [-1.53679418,  0.29351742,  1.03290776, ..., -0.57873591,
        -0.57380915, -1.09598752],
       ...,
       [ 0.60498839, -0.27860412,  0.68712986, ..., -0.57873591,
        -0.57380915, -1.09598752],
       [ 1.25683526,  0.29351742, -0.69598177, ...,  1.72790383,
        -0.57380915,  0.91241915],
       [ 1.46377078, -1.04143285, -0.35020386, ..., -0.57873591,
        -0.57380915, -1.09598752]])

In [50]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [51]:
x_train

array([[ 0.36701255, -0.66001848,  0.34135195, ..., -0.57873591,
        -0.57380915,  0.91241915],
       [-0.19171334,  0.29351742, -0.35020386, ...,  1.72790383,
        -0.57380915,  0.91241915],
       [-0.94702796, -1.42284721, -0.69598177, ..., -0.57873591,
         1.74273971,  0.91241915],
       ...,
       [ 0.87400456, -0.08789694, -1.38753759, ..., -0.57873591,
        -0.57380915, -1.09598752],
       [ 0.17042381,  0.38887101,  1.03290776, ..., -0.57873591,
        -0.57380915,  0.91241915],
       [ 0.48082708,  1.15169974, -1.38753759, ...,  1.72790383,
        -0.57380915,  0.91241915]])

## Builing the ANN model

In [52]:
model=tf.keras.models.Sequential()

In [53]:
#Adding input layer and first hidden layer
model.add(tf.keras.layers.Dense(units=6,activation='relu',input_dim=11))

In [54]:
# Adding the 2nd hidden layer
model.add(tf.keras.layers.Dense(units=6,activation='relu'))

In [55]:
## Output layer
model.add(tf.keras.layers.Dense(units=1,activation='sigmoid'))

In [61]:
# Compiling the model
model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

In [62]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_3 (Dense)             (None, 6)                 72        
                                                                 
 dense_4 (Dense)             (None, 6)                 42        
                                                                 
 dense_5 (Dense)             (None, 1)                 7         
                                                                 
Total params: 121 (484.00 Byte)
Trainable params: 121 (484.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


## Training the Model

In [63]:
model.fit(x_train,y_train.to_numpy(),batch_size=10,epochs=20)

Epoch 1/20
800/800 [==============================] - 2s 2ms/step - loss: 0.5594 - accuracy: 0.7580
Epoch 2/20
800/800 [==============================] - 1s 2ms/step - loss: 0.4572 - accuracy: 0.8031
Epoch 3/20
800/800 [==============================] - 1s 1ms/step - loss: 0.4325 - accuracy: 0.8120
Epoch 4/20
800/800 [==============================] - 1s 1ms/step - loss: 0.4210 - accuracy: 0.8214
Epoch 5/20
800/800 [==============================] - 1s 1ms/step - loss: 0.4094 - accuracy: 0.8292
Epoch 6/20
800/800 [==============================] - 1s 1ms/step - loss: 0.3971 - accuracy: 0.8346
Epoch 7/20
800/800 [==============================] - 1s 1ms/step - loss: 0.3820 - accuracy: 0.8429
Epoch 8/20
800/800 [==============================] - 1s 1ms/step - loss: 0.3684 - accuracy: 0.8484
Epoch 9/20
800/800 [==============================] - 1s 1ms/step - loss: 0.3583 - accuracy: 0.8526
Epoch 10/20
800/800 [==============================] - 1s 1ms/step - loss: 0.3513 - accuracy: 0.8550

## Evaluating the model

In [64]:
test_loss,test_accuracy=model.evaluate(x_test,y_test.to_numpy())

63/63 [==============================] - 0s 1ms/step - loss: 0.3378 - accuracy: 0.8610


In [65]:
test_accuracy

0.8610000014305115

In [66]:
test_loss

0.33780157566070557

In [69]:
y_pred = np.argmax(model.predict(x_test), axis=1)

63/63 [==============================] - 0s 910us/step


In [70]:
y_pred

array([0, 0, 0, ..., 0, 0, 0])

In [72]:
y_test.to_numpy()

array([0, 0, 0, ..., 1, 1, 1])

In [73]:
y_test=y_test.to_numpy()
print(y_test[0],y_pred[0])

0 0


In [75]:
cm=confusion_matrix(y_test,y_pred)
cm

array([[1607,    0],
       [ 393,    0]])